Clean code
Mohaymen-Academy/SE_Team01_Summer1402 pull request #1
Opened 2023-07-19 08:12 UTC by SaraMahmoodabadi

cleaned up the phase 1 code and used interfaces and manager

2023-07-19 10:02 UTC, Ali-Athary commented
nice jobe! everything was ok. 👌

2023-07-21 07:20 UTC, Hossein-29 commented
1. ListCategory class isn't applying second principle of SOLID cause maybe we have other filters and then you should modify these methods to add that filter.

2.As I said before It's better to have an abstraction for docReader cause maybe we have another kind of doc or maybe we want to read it in another way so here you aren't applying fifth principle of SOLID your code should depend of on abstractions not concretes.

2023-07-22 06:49 UTC, Amirack2003 commented on .gitignore.txt
please ignore uploading unnecessary files and data.(ignore book test files)

2023-07-22 07:09 UTC, Amirack2003 commented on src/searchMode/Search.java
> +        this.database = database;
database? you are not using any information from any database please change the name

2023-07-22 07:09 UTC, Amirack2003 commented on src/searchMode/advancedSearch/AdvancedSearch.java
> +        super(database, query);
.

2023-07-22 07:09 UTC, Amirack2003 commented on src/searchMode/advancedSearch/AdvancedSearch.java
> +    public void addToListCategory(String word, ListType type) {
what if we would also have query start with ^query indicates that we prefer documents with query over others? this structure does not handle this and it is in contradiction with SOLID (O)

2023-07-22 07:09 UTC, Amirack2003 commented on textFiles/The Clean Coder.txt
> +The Clean Coder Summary
git ignore T_T

2023-07-22 07:09 UTC, Amirack2003 commented on src/searchMode/NormalSearch.java
> +    public NormalSearch(InvertedIndex database, String query) {
database?

2023-07-22 07:09 UTC, Amirack2003 commented on src/reader/IReader.java
> +public abstract class IReader {
I indicates for interface and it is name convention in C# not Java. Even if then you should use BReader but i do not recommend that.

2023-07-22 07:09 UTC, Amirack2003 commented on src/reader/DocReader.java
> +    private StringBuilder getFileLines(File file) {
There is a class with name StringBuilder in java, please rename this.(it also should be in lamelCase format)

2023-07-22 07:19 UTC, MSPoulaei commented on src/FileManager.java
> +    private final Normalizer normalizer;
- FileManager class should not compose InvertedIndex and Normalizer objects

2023-07-22 07:20 UTC, MSPoulaei commented on src/FileManager.java
> +    }
FileManager should not set defaults for language processing operations

2023-07-22 07:28 UTC, MSPoulaei commented on src/FileManager.java
rename the class name

2023-07-22 07:40 UTC, MSPoulaei commented on src/dataStructures/ListCategory.java
> +        isFirstTime = true;
move this boolean to where addToEssentialFile method was used

2023-07-22 07:44 UTC, MSPoulaei commented on src/filter/normalizer/Normalizer.java
i think it's better we have a single String as input and normalize just one string at a method call
in your LoweCaseNormalizer and UpperCaseNormalizer there is so much duplication in for loop
we can avoid it by processing only one string.

2023-07-22 08:05 UTC, MSPoulaei commented on src/searchMode/NormalSearch.java
> +    public Set<String> geAllDocuments() {
typo in method name

2023-07-22 08:18 UTC, MSPoulaei reviewed
required changes were commented in place.

2023-07-22 11:23 UTC, Ali-Athary requested changes
درست کنید.

2023-07-22 11:23 UTC, Ali-Athary commented on src/searchMode/advancedSearch/AdvancedSearch.java
> +
نکته خط اضافه : اینجا دوتا خط اضافه گذاشتین. باید یدونه باشه.

2023-07-22 11:23 UTC, Ali-Athary commented on src/dataStructures/ListCategory.java
> +    }
اگه هیچ کلمه essential در وردی نباشد، این ست خالی میماند و جواب درست بر نمیگرداند.

2023-07-22 11:23 UTC, Ali-Athary commented on src/searchMode/advancedSearch/AdvancedSearch.java
> +        }
کلاس listCategory بهتره فقط یه تابع برای اضافه کردن داشته باشد و ListType رو به صورت ورودی بگیرد و switch case داخل خود کلاس باشد.

2023-07-22 11:23 UTC, Ali-Athary commented on src/searchMode/NormalSearch.java
> +    private Set<String> queryWords;
بعد تعریف کلاس یه خط خالی باشه.

2023-07-22 11:23 UTC, Ali-Athary commented on src/reader/DocReader.java
شما برای این قسمت فرض کردین همه فایل ها txt هستند بهتره چک شود و توی نام کلاس ذکر شود.

2023-07-22 11:23 UTC, Ali-Athary commented on src/dataStructures/InvertedIndex.java
بهتر بود با inverted index مثل یک ساختمان داده برخورد میکردین و فقط کار های مربوط به ذخیره و بازیابی اطلاعات رو داخلش انجام میدادید و کار های مربوط به Normalizer و Stemmer و ... رو بیرون کلاس انجام میداد.

2023-07-22 11:44 UTC, Ali-Athary approved these changes

2023-07-23 05:56 UTC, MSPoulaei approved these changes
all changes were applied!

2023-07-24 15:20 UTC, Soltaniant reviewed
دمتون گرم و خسته نباشید :+1: 
در مورد نام‌گذاری‌ها یه مقدار مشکل داشتیم. نام‌گذاریمون باید گویا تر باشه و به بهترین حالت بتونه عملکرد اون متود، کلاس یا متغیر رو بیان کنه.

2023-07-24 15:20 UTC, Soltaniant commented on src/DataManager.java
> +
remove the blank line.

2023-07-24 15:20 UTC, Soltaniant commented on src/DataManager.java
> +    //if there was no specific normalizer we use the lowercase normalizer as a default normalizer
redundant comments.

2023-07-24 15:20 UTC, Soltaniant commented on src/DataManager.java
> +    private void fillInvertedIndex(Map<String, StringBuilder> fileText) {
not a good name for parameter `fileText`

2023-07-24 15:20 UTC, Soltaniant commented on src/Main.java
> +
remove blank line

2023-07-24 15:20 UTC, Soltaniant commented on src/Main.java
> +        DataManager fileManager = new DataManager
DataManager fileManager!
we might need to rename these classes. are they specific enough?

2023-07-24 15:20 UTC, Soltaniant commented on src/Main.java
> +                (new SplitTokenizer(), new LoweCaseNormalizer());
Typo: LowCaseNormalizer

2023-07-24 15:20 UTC, Soltaniant commented on src/Main.java
> +        Search search = new AdvancedSearch(fileManager.getInvertedIndex(), query);
`fileManager.getInvertedIndex()`
it seems that we are getting InvertedIndex from a fileManager (actually a dataManager). it sound like a code smell to notice you might need to change something. maybe the architecture or simply a name.

2023-07-24 15:20 UTC, Soltaniant commented on src/Main.java
> +        search.printDocuments(search.getAllDocuments());
printing is not the responsibility of Search class. rename it or do some refactoring on your architecture.

2023-07-24 15:20 UTC, Soltaniant commented on src/DataManager.java
> +public class DataManager {
Read about Middle Man code smell.
`DataManager` has been a middle man.

2023-07-24 15:20 UTC, Soltaniant commented on src/DataManager.java
> +
middle man (obviously)

2023-07-24 15:20 UTC, Soltaniant commented on src/DataManager.java
> +            invertedIndex.addFile(title, fileText.get(title));
`File` is not an appropriate name
+ you can rewrite code without `{}` brackets

2023-07-24 15:20 UTC, Soltaniant commented on src/Main.java
> +        fileManager.createDatabase(new TXTReader(path));
**middleMan**

2023-07-24 15:20 UTC, Soltaniant commented on src/dataStructures/InvertedIndex.java
> +
blank line

2023-07-24 15:20 UTC, Soltaniant commented on src/dataStructures/InvertedIndex.java
> +    private final Map<String, Set<String>> engine;
`engine` might not be a good choice!

2023-07-24 15:20 UTC, Soltaniant commented on src/dataStructures/InvertedIndex.java
> +    }
Getters and setter are usually written last. (in the end lines of class)

2023-07-24 15:20 UTC, Soltaniant commented on src/dataStructures/InvertedIndex.java
> +    private void addWordToEngine(String root, String fileName) {
`root` is not a good name.
also `fileName`

2023-07-24 15:20 UTC, Soltaniant commented on src/dataStructures/InvertedIndex.java
> +    public String getWordRoot(String word) {
each time you use the `getWordRoot` method, you are creating a new instance of Stemmer()

2023-07-24 15:20 UTC, Soltaniant commented on src/dataStructures/InvertedIndex.java
> +    }
the word `FILE` is not a good choice for describing our purpose.

2023-07-24 15:20 UTC, Soltaniant commented on src/dataStructures/InvertedIndex.java
> +
redundant blank line.
(exactly 1 line break is needed between methods)

2023-07-24 15:20 UTC, Soltaniant commented on src/dataStructures/InvertedIndex.java
> +    public void addFile(String title, StringBuilder fileText) {
names!
`addFile`, `title`, `fileText`

2023-07-24 15:20 UTC, Soltaniant commented on src/dataStructures/InvertedIndex.java
> +    private Set<String> manipulateFile(String fileText) {
`manipulateFile` -> not a good name!
also `fileText`

2023-07-24 15:20 UTC, Soltaniant commented on src/dataStructures/ListCategory.java
> +    private final Set<String> forbiddenFiles;
again: the word `File`
your invertedIndex should not be coupled to `File` in anyway!!

2023-07-24 15:20 UTC, Soltaniant commented on src/dataStructures/ListCategory.java
> +public class ListCategory {
not a good name

2023-07-24 15:20 UTC, Soltaniant commented on src/dataStructures/ListCategory.java
> +    public void addToOptionalFile(Set<String> files) {
addToOptionalFile**s**
addToForbiddenFile**s**

2023-07-24 15:20 UTC, Soltaniant commented on src/filter/WordValidator.java
> +public class WordValidator {
is `WordValidator` name, good enough?

2023-07-24 15:20 UTC, Soltaniant commented on src/reader/Reader.java
> +public abstract class Reader {
`Reader` name does not essentially imply fileReader!

2023-07-24 15:20 UTC, Soltaniant commented on src/searchMode/advancedSearch/ListType.java
> +public enum ListType {
not a good name

2023-07-29 09:04 UTC, merged