Phase03
Mohaymen-Academy/SE_Team01_Summer1402 pull request #3
Opened 2023-07-26 12:37 UTC by SaraMahmoodabadi

please review phase03

2023-07-27 12:49 UTC, Soltaniant requested changes
خداقوت و خسته نباشید.

2023-07-27 12:49 UTC, Soltaniant commented on src/main/java/Main.java
> +        System.out.println("Execution time is " + formatter.format((endTime - startTime) / 1000d) + " seconds");
داریم زمان سرچ رو محاسبه می‌کنیم که کار خلاقانه‌ای هست. اما فکر می‌کنم مبدا درستی رو انتخاب نکردیم، چون مدت زمانی که کاربر داره فکر می‌کنه و ورودی رو تایپ می‌کنه رو هم داریم با این زمان محاسبه می‌کنیم. که منطقی نیست ...
احتمالا می‌خواستین فقط زمان خود سرچ (پیدا کردن نتیجه رو) محاسبه کنین.

2023-07-27 12:49 UTC, Soltaniant commented on src/main/java/DataManager.java
> +    public void createDatabase(Reader reader) {
این عبارت رو ببینیم:  createDatabase
از چنین اسمی، این برداشت می‌شه که باید دیتابیس رو بسازه، یعنی مقدمات اولیه‌ش رو آماده کنه. و از اون مهم‌تر، داریم به همچین تابعی reader پاس می‌دیم. بازم با اسمش نمی‌خونه. چرا مستقیما خارج از این کلاس، `reader.getMapDocuments()` رو صدا نمی‌زنیم و فقط نتیجش رو بدیم به invertedIndex، در ادامه هم فقط همین یه تابع `fillInvertedIndex` توی این کلاس می‌مونه و حتی میشه کلاس رو بیخیال شد!

2023-07-27 12:49 UTC, Soltaniant commented on src/main/java/dataStructures/InvertedIndex.java
> +    }
allArgs یا Required نمیشه استفاده کرد؟

2023-07-27 12:49 UTC, Soltaniant commented on src/main/java/dataStructures/InvertedIndex.java
> +    private void addWordToEngine(Map<String, Long> words, String title, long size) {
addWordToEngine
اما اسم اولین ورودی تابع words هست. منطقا نمی‌خورن بهم!

2023-07-27 12:49 UTC, Soltaniant commented on src/main/java/dataStructures/InvertedIndex.java
> +            }
extract method

2023-07-27 12:49 UTC, Soltaniant commented on src/main/java/dataStructures/InvertedIndex.java
> +    public Map<String, Map<String, Score>> getIndexMap() {
getter نیست؟

2023-07-27 12:49 UTC, Soltaniant commented on src/main/java/dataStructures/InvertedIndex.java
> +    public String wordStemmer(String word) {
بهتره اسم این تابع یه verb باشه، چون داره یه عملی انجام می‌ده روی کلمه

2023-07-27 12:49 UTC, Soltaniant commented on src/main/java/dataStructures/InvertedIndex.java
> +            }
معمولا توی for ها امکان extract شدن رو داره. اینجا هم اگر صلاح دیدین این کار رو بکنین.

2023-07-27 12:49 UTC, Soltaniant commented on src/main/java/dataStructures/ListClassifier.java
> +        hasEssentialWords = true;
به جای استفاده از یه متغیر برای بررسی اینکه لیستمون خالی هست یا نه می‌تونیم از خود همون  hashSet این اطلاعات رو بگیریم.

2023-07-27 12:49 UTC, Soltaniant commented on src/main/java/filter/WordValidator.java
> +    private final boolean calledForValidator;
کارکرد این رو متوجه نشدم. ممنون میشم توضیح بدین بعدا

2023-07-27 12:49 UTC, Soltaniant commented on src/main/java/filter/normalizer/LowerCaseNormalizer.java
> +public class LowerCaseNormalizer implements Normalizer {
خیلی اسم خوبیه :+1:

2023-07-27 12:49 UTC, Soltaniant commented on src/main/java/filter/tokenizer/NGramTokenizer.java
> +
این فاصله نباشه ترجیحا.
بین import های عادی فاصله‌ای نمی‌ذارن معمولا، ولی بین staticها و عادیا یه خط فاصله می‌ذارن.
استایل گوگله احتمالا اینی که گفتم :|

2023-07-27 12:49 UTC, Soltaniant commented on src/main/java/filter/tokenizer/NGramTokenizer.java
> +
فاصله گذاری:
- بین کلاس و خط اول کلاس یه خط
- بین فیلد‌ها و توابع یه خط (اینجا الان دو خط داریم مثلا)
- بین خود توابع هم یکی (که رعایت کردین)

2023-07-27 12:49 UTC, Soltaniant commented on src/main/java/filter/tokenizer/SplitTokenizer.java
> +    private final String regex;
فاصله

2023-07-27 12:49 UTC, Soltaniant commented on src/main/java/filter/tokenizer/SplitTokenizer.java
> +                .collect(Collectors.groupingBy(Function.identity(), Collectors.counting()));
احسنت! :100:

2023-07-27 12:49 UTC, Soltaniant commented on src/main/java/reader/TXTReader.java
> +    private boolean fileIsValid(String fileName) {
`isFileValid`

2023-07-27 12:49 UTC, Soltaniant commented on src/main/java/reader/TXTReader.java
> +    private File[] getFiles() {
خوبه که آدرس رو به عنوان ورودی بگیریم که اگر خواستیم چندجا از این reader استفاده کنیم لزوما مجبور نشیم دوباره new کنیم.

2023-07-27 12:49 UTC, Soltaniant commented on src/main/java/search/Sorter.java
> +
فاصله

2023-07-27 12:49 UTC, Soltaniant commented on src/main/java/search/Sorter.java
> +    private final Set<String> queryWords;
فاصله

2023-07-27 12:49 UTC, Soltaniant commented on src/main/java/search/Sorter.java
> +    }
بحث مرتب‌سازیمون جوری نیست که بعدا اگر بخوایم الگوریتم متفاوتی برای سورت استفاده کنیم بشه گسترشش داد.

open/closed

2023-07-27 12:49 UTC, Soltaniant commented on src/main/java/search/searchMode/Search.java
> +
فاصله

2023-07-27 12:49 UTC, Soltaniant commented on src/main/java/search/searchMode/Search.java
> +    protected final String query;
فاصله

2023-07-27 12:49 UTC, Soltaniant commented on src/main/java/search/searchMode/Search.java
> +        return new Sorter(finalQueryWords, invertedIndex, finalFiles).sort();
برای سورت کردن نباید لازم باشه هر بار من یه sorter رو new کنم دیگه :)
معماری sorter بد بوده احتمال زیاد

2023-07-27 12:49 UTC, Soltaniant commented on src/main/java/search/searchMode/advancedSearch/AdvancedSearch.java
> +            }
فکر کنم بشه این `{}` رو برای for حذف کرد. تست کنید

2023-07-27 12:49 UTC, Soltaniant commented on src/main/java/tmo.java
> +//
کد کامنت‌شده

2023-07-27 12:49 UTC, Soltaniant commented on src/main/java/tmo.java
> +        x.setCurrent("dogm");
:|||||||
چه مثالیه ‌آخه :face_in_clouds:

2023-07-27 12:49 UTC, Soltaniant requested changes
خداقوت و خسته نباشید.

2023-07-29 07:59 UTC, sanoooavi commented on src/main/java/dataStructures/ListClassifier.java
> +        hasEssentialWords = true;
اینجا منظورمون این نیست که خالی باشه صرفا یعنی تاحالا کلمه ی essential  داشتیم یا نه.

2023-07-29 08:35 UTC, sanoooavi commented on src/main/java/filter/WordValidator.java
> +    private final boolean calledForValidator;
wordValidator کلا وظیفش اینه که چک کنه یسری کلمات حرف اضافه یا همون stop words هستند یا نه

2023-07-29 09:04 UTC, merged